"""Single source of truth for ALGO_TOOLBOX.xlsx. Edit here, then run build_toolbox.py.

Source status values:
  baseline  = written from the standard method; book page cite pending extraction
  extracted = taken from the owner's book via extract/ with page cite
"""

PHASES = ["Define", "Measure", "Analyze", "Improve", "Control"]

# ---------------------------------------------------------------- Six Sigma (DMAIC)
# ct: computational-thinking ids; st: statistics ids
SIX_SIGMA = [
    # Define
    dict(phase="Define", tool="Project charter", purpose="Fix the problem, goal, scope, and owner before work starts.",
         formula="Problem = what, where, when, how big (baseline metric). Goal = metric, baseline, target, date.",
         rule="Charter approved when the goal is a measurable metric with baseline and target.",
         output="Signed charter", ct=["CT-ABS", "CT-STOP"], st=[]),
    dict(phase="Define", tool="SIPOC", purpose="Bound the process: Suppliers, Inputs, Process (5 to 7 steps), Outputs, Customers.",
         formula="Map 5 to 7 high-level steps; list inputs and outputs per step.",
         rule="Scope fixed when start and end points are named.",
         output="SIPOC diagram", ct=["CT-DEC", "CT-ABS"], st=[]),
    dict(phase="Define", tool="VOC to CTQ tree", purpose="Turn customer needs into measurable Critical-to-Quality requirements.",
         formula="Need -> driver -> CTQ (metric + spec limits LSL/USL).",
         rule="Each leaf has an operational definition and spec limits.",
         output="CTQ tree", ct=["CT-DEC", "CT-REC", "CT-ABS"], st=[]),
    dict(phase="Define", tool="Kano model", purpose="Classify requirements as basic, performance, or delighter.",
         formula="Paired functional / dysfunctional survey questions -> Kano category table.",
         rule="Basic needs are met first; performance needs are optimized.",
         output="Ranked requirement list", ct=["CT-PAT", "CT-SORT"], st=["ST-DESC"]),
    dict(phase="Define", tool="Cost of poor quality (COPQ)", purpose="Size the prize in money.",
         formula="COPQ = defect rate x cost per defect x annual volume (+ appraisal + prevention).",
         rule="Project proceeds when COPQ exceeds project cost.",
         output="COPQ estimate", ct=["CT-TRADE"], st=[]),
    # Measure
    dict(phase="Measure", tool="Operational definitions", purpose="Make every metric measurable the same way by anyone.",
         formula="Metric = what is measured + method + instrument + unit + pass/fail criterion.",
         rule="Two people measuring the same unit get the same answer.",
         output="Definition table", ct=["CT-ABS", "CT-REP"], st=[]),
    dict(phase="Measure", tool="Data collection plan and sample size", purpose="Collect enough of the right data.",
         formula="Mean: n = (z* sigma / E)^2. Proportion: n = z*^2 p(1-p) / E^2. Round up.",
         rule="n meets the margin of error E at the chosen confidence.",
         output="Plan with n, frequency, owner", ct=["CT-ALG", "CT-REP"], st=["ST-SAMP", "ST-POWER"]),
    dict(phase="Measure", tool="Gage R&R (MSA, ANOVA method)", purpose="Prove the measurement system is good enough.",
         formula="%GRR = sigma_GRR / sigma_total x 100. ndc = 1.41 x sigma_part / sigma_GRR.",
         rule="%GRR < 10% accept; 10 to 30% conditional; > 30% reject (AIAG). ndc >= 5.",
         output="MSA report", ct=["CT-EVAL", "CT-TEST"], st=["ST-ANOVA1", "ST-ANOVA2"]),
    dict(phase="Measure", tool="Attribute agreement analysis", purpose="Prove pass/fail judgments are consistent.",
         formula="Cohen's kappa = (p_o - p_e) / (1 - p_e); Fleiss' kappa for 3+ appraisers.",
         rule="kappa >= 0.75 good; 0.40 to 0.75 marginal; < 0.40 poor.",
         output="Agreement report", ct=["CT-EVAL"], st=["ST-CHI"]),
    dict(phase="Measure", tool="Normality check", purpose="Decide whether normal-theory methods apply.",
         formula="Normal probability plot; Anderson-Darling or Shapiro-Wilk test.",
         rule="p > alpha and a straight plot -> treat as normal; else transform or go nonparametric.",
         output="Plot + test result", ct=["CT-PAT", "CT-EVAL"], st=["ST-NORM"]),
    dict(phase="Measure", tool="Baseline capability", purpose="Measure how well the process meets spec today.",
         formula="Cp = (USL - LSL) / 6 sigma_within. Cpk = min(USL - mean, mean - LSL) / 3 sigma_within. Pp, Ppk use overall sigma.",
         rule="Cpk >= 1.33 capable; 1.00 to 1.33 marginal; < 1.00 not capable. Requires a stable process first.",
         output="Capability report", ct=["CT-EVAL", "CT-ABS"], st=["ST-CAP", "ST-NORM"]),
    dict(phase="Measure", tool="DPMO and sigma level", purpose="Express defect performance on one scale.",
         formula="DPMO = defects / (units x opportunities) x 10^6. Sigma level = NORM.S.INV(1 - DPMO/10^6) + 1.5.",
         rule="The 1.5 shift is the long-term convention; state it when used.",
         output="Baseline sigma", ct=["CT-ABS"], st=["ST-NORM"]),
    # Analyze
    dict(phase="Analyze", tool="Pareto analysis", purpose="Find the vital few causes.",
         formula="Count per category, sort descending, cumulative % = running sum / total.",
         rule="Work the categories that reach about 80% cumulative first.",
         output="Pareto chart", ct=["CT-SORT", "CT-GREEDY", "CT-PAT"], st=["ST-DESC"]),
    dict(phase="Analyze", tool="Fishbone (Ishikawa)", purpose="List all candidate causes by category.",
         formula="Branches: Man, Machine, Method, Material, Measurement, Mother Nature (6M).",
         rule="Every branch is examined before any cause is chosen.",
         output="Cause list", ct=["CT-DEC", "CT-BFS"], st=[]),
    dict(phase="Analyze", tool="5 Whys", purpose="Drill one cause chain to its root.",
         formula="Ask why until the answer is an actionable, controllable cause.",
         rule="Stop at a cause you can change and verify with data.",
         output="Root cause chain", ct=["CT-DFS", "CT-REC", "CT-STOP"], st=[]),
    dict(phase="Analyze", tool="FMEA", purpose="Rank failure modes by risk.",
         formula="RPN = Severity x Occurrence x Detection (each 1 to 10). AIAG-VDA 2019 uses Action Priority tables instead.",
         rule="Act on highest RPN or High Action Priority; any Severity 9 to 10 gets action regardless.",
         output="FMEA table", ct=["CT-SORT", "CT-DEC", "CT-HEUR"], st=[]),
    dict(phase="Analyze", tool="Hypothesis testing", purpose="Prove a suspected cause with data.",
         formula="H0 vs Ha; pick the test from the Decision Algorithms sheet; compute statistic and p-value.",
         rule="Reject H0 when p < alpha, after checking assumptions. Report the CI and effect size.",
         output="Verified causes", ct=["CT-EVAL", "CT-TREE", "CT-TEST"], st=["ST-T1", "ST-T2", "ST-TP", "ST-CHI", "ST-ANOVA1", "ST-NP"]),
    dict(phase="Analyze", tool="Correlation and regression", purpose="Quantify how Y depends on X.",
         formula="b1 = r sy / sx; b0 = ybar - b1 xbar; R^2; t = b1 / SE(b1).",
         rule="Slope significant at alpha and residuals show no pattern.",
         output="Y = f(X) model", ct=["CT-MODEL", "CT-PAT"], st=["ST-REG", "ST-MREG"]),
    dict(phase="Analyze", tool="Multi-vari chart", purpose="See which family of variation dominates.",
         formula="Plot within-piece, piece-to-piece, and time-to-time variation together.",
         rule="Investigate the family with the largest spread first.",
         output="Variation family", ct=["CT-PAT", "CT-DEC"], st=["ST-DESC"]),
    dict(phase="Analyze", tool="Half-split / component search", purpose="Isolate the faulty stage or part fast.",
         formula="Test the midpoint; keep the failing half; repeat. Steps = ceil(log2 N).",
         rule="Stop when one component remains and swapping it moves the fault.",
         output="Isolated cause", ct=["CT-DIV", "CT-BSEARCH", "CT-DEBUG"], st=[]),
    # Improve
    dict(phase="Improve", tool="Design of experiments (2^k factorial)", purpose="Find which factors move Y and by how much.",
         formula="Effect = mean(Y at +) - mean(Y at -). Runs = 2^k (x replicates). ANOVA on effects.",
         rule="Keep factors whose effects are significant; confirm with a confirmation run.",
         output="Optimal settings", ct=["CT-MODEL", "CT-OPT", "CT-ITER"], st=["ST-ANOVA2", "ST-MREG"]),
    dict(phase="Improve", tool="Response surface / steepest ascent", purpose="Climb to the optimum setting.",
         formula="Move along the gradient of the fitted first-order model; fit second order near the peak.",
         rule="Stop when response stops improving beyond noise.",
         output="Optimum", ct=["CT-OPT", "CT-STOP", "CT-ITER"], st=["ST-MREG"]),
    dict(phase="Improve", tool="Pugh / solution selection matrix", purpose="Choose among solutions against criteria.",
         formula="Score each option vs a datum on weighted criteria: + / S / -; sum weighted scores.",
         rule="Pick the highest weighted score; check for a hybrid.",
         output="Chosen solution", ct=["CT-SORT", "CT-TRADE"], st=[]),
    dict(phase="Improve", tool="Pilot and before/after test", purpose="Prove the fix works.",
         formula="Two-sample (Welch) t or paired t on before vs after; two-proportion z for rates. Power analysis sets n.",
         rule="Improvement real when p < alpha and the CI excludes zero in the right direction.",
         output="Verified improvement", ct=["CT-EVAL", "CT-TEST"], st=["ST-T2", "ST-TP", "ST-PROP", "ST-POWER"]),
    dict(phase="Improve", tool="Poka-yoke (mistake proofing)", purpose="Make the error impossible or instantly visible.",
         formula="Control (prevent) or warning (detect) device at the error source.",
         rule="Re-score FMEA Occurrence/Detection after install.",
         output="Mistake-proof device", ct=["CT-ALG", "CT-STATE"], st=[]),
    # Control
    dict(phase="Control", tool="Control chart selection", purpose="Pick the right chart for the data.",
         formula="See Decision Algorithms sheet (I-MR, Xbar-R, Xbar-S, p, np, c, u).",
         rule="Chart follows data type and subgroup size.",
         output="Chosen chart", ct=["CT-TREE", "CT-REP"], st=["ST-SPC"]),
    dict(phase="Control", tool="Xbar-R and I-MR charts", purpose="Detect when the process changes.",
         formula="Xbar-R: UCL/LCL = Xbarbar +/- A2 Rbar; R: UCL = D4 Rbar, LCL = D3 Rbar. I-MR: x +/- 2.66 MRbar; MR UCL = 3.267 MRbar.",
         rule="Western Electric: 1 point beyond 3 sigma; 2 of 3 beyond 2 sigma; 4 of 5 beyond 1 sigma; 8 in a row one side.",
         output="Control chart", ct=["CT-PAT", "CT-INV"], st=["ST-SPC"]),
    dict(phase="Control", tool="p and c charts", purpose="Monitor defective rates and defect counts.",
         formula="p: pbar +/- 3 sqrt(pbar(1 - pbar)/n). c: cbar +/- 3 sqrt(cbar). LCL floors at 0.",
         rule="Same Western Electric rules.",
         output="Attribute chart", ct=["CT-PAT", "CT-INV"], st=["ST-SPC", "ST-PROP"]),
    dict(phase="Control", tool="Control plan and reaction plan", purpose="Keep the gain: who checks what, how often, and what to do.",
         formula="Row per CTQ: spec, method, sample size, frequency, owner, reaction steps.",
         rule="Every out-of-control signal has a written if-then reaction.",
         output="Control plan", ct=["CT-STATE", "CT-ALG", "CT-GEN"], st=[]),
    dict(phase="Control", tool="Sustained capability and hand-off", purpose="Prove the gain holds and transfer ownership.",
         formula="Recompute Cpk/Ppk on post-change data; compare to baseline.",
         rule="Close when Cpk >= target for the agreed period and the owner signs.",
         output="Close-out report", ct=["CT-EVAL", "CT-GEN", "CT-MEMO"], st=["ST-CAP"]),
]

# ---------------------------------------------------------------- Computational thinking
CT = [
    dict(id="CT-DEC", method="Decomposition", definition="Break a problem into smaller parts that can be solved separately.",
         applies="SIPOC, CTQ tree, fishbone branches, and work breakdown all decompose a process or requirement.", phases="Define, Analyze"),
    dict(id="CT-PAT", method="Pattern recognition", definition="Find similarities, trends, and regularities in data or problems.",
         applies="Control-chart run rules, Pareto, multi-vari, and stratification are pattern detectors over process data.", phases="Measure, Analyze, Control"),
    dict(id="CT-ABS", method="Abstraction", definition="Keep the details that matter; drop the rest.",
         applies="Operational definitions, CTQ metrics, and Y = f(X) reduce a process to measurable variables.", phases="Define, Measure"),
    dict(id="CT-ALG", method="Algorithm design", definition="Write an exact, ordered, finite set of steps that solves the problem.",
         applies="DMAIC itself, standard work, data collection plans, and reaction plans are algorithms.", phases="All"),
    dict(id="CT-EVAL", method="Evaluation", definition="Judge whether a solution is correct, efficient, and fit for purpose.",
         applies="Hypothesis tests, MSA, capability, and before/after tests evaluate claims with data.", phases="Measure, Analyze, Improve, Control"),
    dict(id="CT-GEN", method="Generalization", definition="Adapt a solution so it solves a wider class of problems.",
         applies="Replicating a fix to sister processes; control plans as reusable templates.", phases="Control"),
    dict(id="CT-ITER", method="Iteration", definition="Repeat a step until a condition is met.",
         applies="PDCA cycles and sequential DOE rounds iterate toward the target.", phases="Improve"),
    dict(id="CT-REC", method="Recursion", definition="Solve a problem by solving smaller instances of itself, down to a base case.",
         applies="CTQ trees and 5 Whys recurse; the base case is a measurable CTQ or an actionable root cause.", phases="Define, Analyze"),
    dict(id="CT-STOP", method="Termination and stop conditions", definition="Every loop has a condition that guarantees it ends.",
         applies="Charter goals, 5 Whys stopping rule, steepest-ascent stop, and agent term limits (attempts, time, tokens).", phases="Define, Analyze, Improve"),
    dict(id="CT-INV", method="Invariants", definition="A property that must stay true on every pass of a loop.",
         applies="Control limits express the invariant 'process is stable'; a signal means the invariant broke.", phases="Control"),
    dict(id="CT-DIV", method="Divide and conquer", definition="Split the problem, solve the parts, combine the answers.",
         applies="Half-split troubleshooting and component search split a failing system in two each step.", phases="Analyze"),
    dict(id="CT-BSEARCH", method="Binary search", definition="Find a target in sorted space by halving it each step: ceil(log2 N) steps.",
         applies="Locating the first bad stage, lot, commit, or setting in an ordered sequence.", phases="Analyze"),
    dict(id="CT-BFS", method="Breadth-first search", definition="Explore all options at one level before going deeper.",
         applies="Fishbone: list every category's causes before drilling any one.", phases="Analyze"),
    dict(id="CT-DFS", method="Depth-first search", definition="Follow one path to the end before backtracking.",
         applies="5 Whys follows one cause chain to its root, then backtracks to the next.", phases="Analyze"),
    dict(id="CT-SORT", method="Sorting and prioritization", definition="Order items by a key so the most important come first.",
         applies="Pareto, RPN ranking, Kano, and Pugh matrices are sorts by impact or score.", phases="Define, Analyze, Improve"),
    dict(id="CT-GREEDY", method="Greedy strategy", definition="Take the best-looking option at each step.",
         applies="Work the biggest Pareto bar first. Check the result: greedy can miss interactions that DOE finds.", phases="Analyze"),
    dict(id="CT-HEUR", method="Heuristics", definition="Rules of thumb that are usually good enough, not guaranteed optimal.",
         applies="Cpk 1.33, %GRR 10/30, RPN thresholds, and the 80/20 rule are heuristics; state them as such.", phases="All"),
    dict(id="CT-TREE", method="Decision trees", definition="A branching sequence of questions that leads to one action.",
         applies="Hypothesis-test and control-chart selection roadmaps are decision trees.", phases="Analyze, Control"),
    dict(id="CT-REP", method="Data representation", definition="Choose how data is stored and typed so the right operations apply.",
         applies="Continuous vs attribute data decides the test and the chart; check sheets structure collection.", phases="Measure, Control"),
    dict(id="CT-MODEL", method="Modeling and simulation", definition="Build a simplified model and run it to predict behavior.",
         applies="Regression and DOE models; Monte Carlo tolerance stack-ups.", phases="Analyze, Improve"),
    dict(id="CT-OPT", method="Optimization / search over a space", definition="Find the input settings that maximize or minimize an objective.",
         applies="DOE and response surface methods search factor space for the optimum.", phases="Improve"),
    dict(id="CT-DEBUG", method="Debugging", definition="Reproduce, isolate, fix, and verify a fault.",
         applies="Root cause analysis is debugging a process: reproduce the defect, isolate the cause, fix, verify with data.", phases="Analyze, Improve"),
    dict(id="CT-TEST", method="Testing and verification", definition="Check outputs against expected results with cases that can fail.",
         applies="Gage studies, confirmation runs, and before/after tests are test cases on the process.", phases="Measure, Improve"),
    dict(id="CT-STATE", method="State machines", definition="A system as a set of states and the events that move between them.",
         applies="Reaction plans and poka-yoke devices define states (in control, signal, contained) and transitions.", phases="Improve, Control"),
    dict(id="CT-TRADE", method="Complexity and trade-offs", definition="Weigh cost (time, money, effort) against benefit.",
         applies="COPQ, Pugh weighting, and choosing sample size vs cost.", phases="Define, Improve"),
    dict(id="CT-MEMO", method="Memoization / caching", definition="Store a computed result so it is reused, not recomputed.",
         applies="Lessons-learned logs and the failure frequency chart reuse past root causes.", phases="Control"),
]

# ---------------------------------------------------------------- Statistics (Moore, McCabe & Craig, IPS)
# chapter = likely chapter in recent editions; verify against the owner's edition.
STATS = [
    dict(id="ST-DESC", method="Descriptive statistics", use="Summarize a distribution.",
         assume="None.", formula="mean, s = sqrt(sum (x - xbar)^2 / (n - 1)); five-number summary; outlier if beyond Q1 - 1.5 IQR or Q3 + 1.5 IQR.",
         rule="Describe shape, center, spread, outliers before any test.", chapter="1-2"),
    dict(id="ST-NORM", method="Normal distribution and z", use="Probabilities and percentiles for normal data.",
         assume="Data approximately normal (check plot).", formula="z = (x - mu) / sigma.",
         rule="Use the normal table or NORM.S.DIST.", chapter="1"),
    dict(id="ST-SAMP", method="Sampling distributions and CLT", use="Know how a statistic varies from sample to sample.",
         assume="Random sample; n large enough for CLT.", formula="SD(xbar) = sigma / sqrt(n).",
         rule="Larger n narrows the sampling distribution by sqrt(n).", chapter="3, 5"),
    dict(id="ST-T1", method="One-sample t (CI and test)", use="Estimate or test one mean.",
         assume="Random sample; normal or n >= 30 without strong skew.", formula="xbar +/- t* s / sqrt(n), df = n - 1. t = (xbar - mu0) / (s / sqrt(n)).",
         rule="Reject H0 when p < alpha.", chapter="7"),
    dict(id="ST-TP", method="Paired t", use="Before/after on the same units.",
         assume="Differences approximately normal.", formula="t = dbar / (s_d / sqrt(n)), df = n - 1.",
         rule="Reject H0 when p < alpha.", chapter="7"),
    dict(id="ST-T2", method="Two-sample t (Welch)", use="Compare two independent means.",
         assume="Independent random samples; each roughly normal or large.", formula="t = (xbar1 - xbar2) / sqrt(s1^2/n1 + s2^2/n2); df by Welch or conservative min(n1, n2) - 1.",
         rule="Reject H0 when p < alpha.", chapter="7"),
    dict(id="ST-PROP", method="Inference for proportions", use="Estimate or compare defect rates.",
         assume="Counts of successes and failures >= 10 (or use plus-four).", formula="phat +/- z* sqrt(phat(1 - phat)/n). Two-proportion z with pooled p.",
         rule="Reject H0 when p < alpha.", chapter="8"),
    dict(id="ST-CHI", method="Chi-square test for two-way tables", use="Test association between two categorical variables.",
         assume="Expected counts mostly >= 5.", formula="X^2 = sum (O - E)^2 / E, E = row total x column total / n, df = (r - 1)(c - 1).",
         rule="Reject independence when p < alpha.", chapter="9"),
    dict(id="ST-REG", method="Simple linear regression inference", use="Test and estimate a straight-line relationship.",
         assume="Linearity, independence, normal residuals, equal variance (check residual plots).", formula="b1 = r sy / sx; t = b1 / SE(b1), df = n - 2.",
         rule="Slope significant when p < alpha.", chapter="10"),
    dict(id="ST-MREG", method="Multiple regression", use="Model Y from several X.",
         assume="As simple regression; check multicollinearity.", formula="Overall F test; t test per coefficient; R^2 and adjusted R^2.",
         rule="Keep terms significant at alpha that make physical sense.", chapter="11"),
    dict(id="ST-ANOVA1", method="One-way ANOVA", use="Compare 3+ means.",
         assume="Independent samples, normal, equal SDs (largest/smallest s < 2).", formula="F = MSG / MSE.",
         rule="Reject equal means when p < alpha; follow with multiple comparisons (Tukey or Bonferroni).", chapter="12"),
    dict(id="ST-ANOVA2", method="Two-way ANOVA", use="Two factors and their interaction.",
         assume="As one-way.", formula="Separate F tests for A, B, and A x B.",
         rule="Interpret the interaction first.", chapter="13"),
    dict(id="ST-NP", method="Nonparametric tests", use="When normality fails and n is small.",
         assume="Independent samples; similar shapes for location claims.", formula="Wilcoxon rank sum, Wilcoxon signed rank, Kruskal-Wallis.",
         rule="Reject H0 when p < alpha.", chapter="15"),
    dict(id="ST-BOOT", method="Bootstrap and permutation tests", use="CIs and tests without distribution assumptions.",
         assume="Sample represents the population.", formula="Resample with replacement B >= 1000 times; percentile CI.",
         rule="Use when formulas do not apply.", chapter="16"),
    dict(id="ST-POWER", method="Power and sample size", use="Choose n before collecting data.",
         assume="Planned effect size and sigma.", formula="Power = P(reject H0 | Ha true); pick n for power >= 0.80.",
         rule="Underpowered study: a non-significant result proves nothing.", chapter="6"),
    dict(id="ST-SPC", method="Statistical process control", use="Monitor a process over time.",
         assume="Rational subgroups; Phase I establishes limits.", formula="3-sigma control limits from within-subgroup variation.",
         rule="Out-of-control signal triggers the reaction plan.", chapter="17 (companion)"),
    dict(id="ST-CAP", method="Process capability", use="Compare process spread to spec.",
         assume="Process in control; distribution known (often normal).", formula="Cp, Cpk, Pp, Ppk (see Six Sigma sheet).",
         rule="Compute only after control is shown.", chapter="17 (companion)"),
]

# ---------------------------------------------------------------- Decision algorithms
TEST_ROADMAP = [
    # (Y type, X type, groups/case, normal & equal-variance path, nonparametric path)
    ("Continuous", "None (vs target)", "1 sample", "One-sample t (ST-T1)", "Wilcoxon signed rank (ST-NP)"),
    ("Continuous", "Categorical", "2 paired", "Paired t (ST-TP)", "Wilcoxon signed rank (ST-NP)"),
    ("Continuous", "Categorical", "2 independent", "Welch two-sample t (ST-T2)", "Wilcoxon rank sum / Mann-Whitney (ST-NP)"),
    ("Continuous", "Categorical", "3+ groups", "One-way ANOVA (ST-ANOVA1)", "Kruskal-Wallis (ST-NP)"),
    ("Continuous", "Categorical", "2 factors", "Two-way ANOVA (ST-ANOVA2)", "Transform or bootstrap (ST-BOOT)"),
    ("Continuous", "Continuous", "1 X", "Simple regression (ST-REG)", "Spearman rank correlation"),
    ("Continuous", "Continuous", "2+ X", "Multiple regression / DOE (ST-MREG)", "Bootstrap coefficients (ST-BOOT)"),
    ("Attribute (pass/fail)", "None (vs target)", "1 proportion", "One-proportion z (ST-PROP)", "Exact binomial test"),
    ("Attribute (pass/fail)", "Categorical", "2 groups", "Two-proportion z (ST-PROP)", "Fisher's exact test"),
    ("Attribute (counts)", "Categorical", "2+ groups", "Chi-square two-way table (ST-CHI)", "Fisher's exact test"),
    ("Attribute (pass/fail)", "Continuous", "1+ X", "Logistic regression", "-"),
]
CHART_ROADMAP = [
    ("Continuous", "n = 1", "I-MR", "x +/- 2.66 MRbar; MR UCL = 3.267 MRbar", "One reading per period; slow or costly measurements."),
    ("Continuous", "2 to 9", "Xbar-R", "Xbarbar +/- A2 Rbar; R: D3 Rbar to D4 Rbar", "Small rational subgroups (most common)."),
    ("Continuous", "10 or more", "Xbar-S", "Xbarbar +/- A3 sbar; S: B3 sbar to B4 sbar", "Large subgroups; s estimates spread better than R."),
    ("Defectives (pass/fail)", "Constant n", "np", "n pbar +/- 3 sqrt(n pbar (1 - pbar))", "Count of defective units, fixed sample size."),
    ("Defectives (pass/fail)", "Varying n", "p", "pbar +/- 3 sqrt(pbar (1 - pbar) / n_i)", "Fraction defective; limits change with each n_i."),
    ("Defects (counts)", "Constant area", "c", "cbar +/- 3 sqrt(cbar)", "Defects per unit, same inspection area each time."),
    ("Defects (counts)", "Varying area", "u", "ubar +/- 3 sqrt(ubar / n_i)", "Defects per unit when inspection area varies."),
]
PROJECT_LOOP = [
    # step, action, check, pass ->, fail ->
    ("1", "Write the objective, metric, baseline, target, and done-when line.", "All five written?", "2", "Stop: ask the owner"),
    ("2", "Set term limits: attempts (6), time budget, token budget.", "Limits written?", "3", "Set defaults, then 3"),
    ("3", "Attempt the next sub-problem.", "Done-when true?", "6", "4"),
    ("4", "Log the failure in FAILURES.xlsx (category, root cause).", "Same root cause seen before?", "Apply the logged fix, then 3", "5"),
    ("5", "Check term limits.", "Any limit reached?", "7", "3"),
    ("6", "Run Part B self-audit (objective, history, claim ledger, sweep).", "Every claim verified?", "8", "3"),
    ("7", "Write the hand-off plan (B6).", "A fresh agent could finish from it?", "8", "7"),
    ("8", "Run Parts C and D; report.", "Report block complete?", "End", "8"),
]

FAILURE_CATEGORIES = [
    "Claimed work not done",
    "Absence treated as proof",
    "Unknown left in a table",
    "Objective drift",
    "Exit attempt / premature stop",
    "Unreadable image or CAD view",
    "Math or unit error",
    "Unsourced value",
    "Artifact not secured / not pushed",
    "Wrong location / duplicate created",
    "Skill or procedure skipped",
    "Tool or environment failure",
]
# Seed rows: failures the owner reported on 2026-10-08 (Grok two-arm digital gantry session).
FAILURE_SEED = [
    ("2026-10-08", "two-arm-digital-gantry", "Grok", "Absence treated as proof", "A 404 on a hardware repo was recorded as 'name never created'.", "Lookup failure read as a fact about the world.", "Rule B3: record 'not found by <method>'.", "Y"),
    ("2026-10-08", "two-arm-digital-gantry", "Grok", "Claimed work not done", "CAD was reported but no CAD file existed.", "No claim ledger; claims not tied to paths.", "Rule B3: every claim needs a file path.", "Y"),
    ("2026-10-08", "two-arm-digital-gantry", "Grok", "Unknown left in a table", "Motor table published with servo repo 'unknown' and no dimensions.", "Agent stopped at search instead of designing.", "Rule A7: source, design, or give search terms.", "Y"),
    ("2026-10-08", "two-arm-digital-gantry", "Grok", "Unreadable image or CAD view", "Image output was not readable; wasted owner time.", "No pagination check before reporting.", "Rule A8: open and check every image.", "Y"),
    ("2026-10-08", "two-arm-digital-gantry", "Grok", "Exit attempt / premature stop", "Agent kept trying to end before solving the problem.", "Vague completion criteria.", "Done-when line on every step; loop control.", "Y"),
    ("2026-10-08", "two-arm-digital-gantry", "Grok", "Objective drift", "Session did not deliver the original objective.", "No objective restatement before reporting.", "Rule B1 and B5: objective score.", "Y"),
]

SOURCES = [
    ("Six Sigma methodology (owner's Six Sigma books)", "Six Sigma, Crosswalk", "baseline", "Book titles and paths needed; run extract/ with --lexicon six_sigma."),
    ("Moore, McCabe & Craig, Introduction to the Practice of Statistics", "Statistics", "baseline", "Chapters are likely numbers for recent editions; verify against the owner's edition. Codex stats extraction will replace this sheet."),
    ("Owner's engineering statistics text", "Statistics", "pending", "Title needed."),
    ("Introduction to Computational Thinking (owner's copy)", "Computational Thinking", "baseline", "Book not in this container. Rows are the standard computational-thinking methods (Wing 2006 and common algorithm design). Run extract/ with --lexicon computational_thinking and replace."),
    ("AIAG MSA (4th ed.) and AIAG-VDA FMEA (2019)", "Six Sigma", "baseline", "Thresholds for %GRR, ndc, and FMEA Action Priority."),
    ("Owner failure reports, 2026-10-08", "Failure Log, Failure Pareto", "owner-reported", "Seed rows from the Grok two-arm digital gantry session."),
]
